### ISSUE TITLE
ESLint modified rules

### ISSUE THREAD

**Issue by Roverr** [CodingSans/eslint-config-codingsans#1]
Some of the rules' name are modified, so the linter's rules should be updated.

**Comment by latotty** [comment]
https://github.com/CodingSans/eslint-config-codingsans/pull/3

**Comment by latotty** [comment]
Will be resolved by https://github.com/CodingSans/eslint-config-codingsans/pull/3

**Comment by Roverr** [comment]
Thank you :+1:

**Comment by latotty** [comment]
Fixed
